name: gpu-tracker-ph

volumes:
  db-data:
  venv-data:

services:
  api:
    build: .
    image: kvdomingo/gpu-tracker-ph-api:latest
    restart: unless-stopped
    volumes:
      - .:/app
      - venv-data:/app/.venv
    command:
      - >
        uv sync --dev --frozen;
        exec uv run fastapi dev --host 0.0.0.0 --port 8000 api/app.py;
    environment:
      PYTHON_ENV: ${PYTHON_ENV}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8000:8000

  ui:
    image: oven/bun:1-alpine
    restart: unless-stopped
    working_dir: /app
    command:
      - /bin/sh
      - -eu
      - -c
      - >
        bun install;
        exec bun run dev;
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000

  redis:
    image: redis:8
    restart: unless-stopped
    volumes:
      - db-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 2s
      retries: 3
    ports:
      - 6379:6379
