version: "3.8"

services:
  apiserver:
    build:
      context: .
      target: dev
    image: kvdomingo/gpu-tracker-ph-api:latest
    env_file: .env
    volumes:
      - .:/backend

  frontend:
    build: ./web/app
    image: kvdomingo/gpu-tracker-ph-web:latest
    env_file: ./web/app/.env
    volumes:
      - ./web/app:/web

  proxy:
    image: nginx:latest
    ports:
      - 8000:8000
    command:
      - nginx
      - "-g"
      - daemon off;
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apiserver
    restart: unless-stopped

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - db-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  db-data:
