version: "3"

tasks:
  default:
    cmd:
      task: up

  up:
    desc: Create and start containers
    cmds:
      - infisical run -- docker compose up --detach --build --remove-orphans {{ .CLI_ARGS }}

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose logs --follow {{ .CLI_ARGS }}

  stop:
    desc: Stop containers
    cmds:
      - docker compose stop {{ .CLI_ARGS }}

  restart:
    desc: Restart containers
    cmds:
      - docker compose restart {{ .CLI_ARGS }}

  clean:
    desc: Shutdown and remove all containers
    cmds:
      - docker compose down --volumes --remove-orphans {{ .CLI_ARGS }}
